### ISSUE TITLE
sns jointplot is producing error..pls help

### ISSUE THREAD

**Issue by jayagupta678** [jayagupta678/Python_codes#1]
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

df = pd.DataFrame({'C1': {'a': 1,'b': 15,'c': 9,'d': 7,'e': 2,'f': 2,'g': 6,'h': 5,'k': 5,'l': 8},
          'C2': {'a': 6,'b': 18,'c': 13,'d': 8,'e': 6,'f': 6,'g': 8,'h': 9,'k': 13,'l': 15}})

fig = plt.figure()
ax1 = fig.add_subplot(121)
ax2 = fig.add_subplot(122)

JG1 = sns.jointplot("C1", "C2", data=df, kind='reg')
JG2 = sns.jointplot("C1", "C2", data=df, kind='kde')

#subplots migration
f = plt.figure()
for J in [JG1, JG2]:
    for A in J.fig.axes:
        f._axstack.add(f._make_key(A), A)

#subplots size adjustment
f.axes[0].set_position([0.05, 0.05, 0.4,  0.4])
f.axes[1].set_position([0.05, 0.45, 0.4,  0.05])
f.axes[2].set_position([0.45, 0.05, 0.05, 0.4])
f.axes[3].set_position([0.55, 0.05, 0.4,  0.4])
f.axes[4].set_position([0.55, 0.45, 0.4,  0.05])
f.axes[5].set_position([0.95, 0.05, 0.05, 0.4])

**Comment by jayagupta678** [comment]
this sns.joitplot is producing error

Traceback (most recent call last):
File "C:/Users/JG/PycharmProjects/Demo/5.py", line 12, in <module>
JG1 = sns.jointplot("C1", "C2", data=df, kind='reg')
File "C:\ProgramData\Anaconda3\lib\site-packages\seaborn\distributions.py", line 839, in jointplot
grid.plot_marginals(distplot, **marginal_kws)
File "C:\ProgramData\Anaconda3\lib\site-packages\seaborn\axisgrid.py", line 1752, in plot_marginals
func(self.x, **kwargs)
File "C:\ProgramData\Anaconda3\lib\site-packages\seaborn\distributions.py", line 221, in distplot
kdeplot(a, vertical=vertical, ax=ax, color=kde_color, **kde_kws)
File "C:\ProgramData\Anaconda3\lib\site-packages\seaborn\distributions.py", line 604, in kdeplot
cumulative=cumulative, **kwargs)
File "C:\ProgramData\Anaconda3\lib\site-packages\seaborn\distributions.py", line 270, in _univariate_kdeplot
cumulative=cumulative)
File "C:\ProgramData\Anaconda3\lib\site-packages\seaborn\distributions.py", line 328, in _statsmodels_univariate_kde
kde.fit(kernel, bw, fft, gridsize=gridsize, cut=cut, clip=clip)
File "C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\nonparametric\kde.py", line 146, in fit
clip=clip, cut=cut)
File "C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\nonparametric\kde.py", line 506, in kdensityfft
f = revrt(zstar)
File "C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\nonparametric\kdetools.py", line 20, in revrt
y = X[:m/2+1] + np.r_[0,X[m/2+1:],0]*1j
TypeError: slice indices must be integers or None or have an __index__ method

.Any help will be appreciated.
